-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 02:21:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`kategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kategory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kategory` (
  `kategory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zayavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zayavka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zayavka` (
  `zayavka_id` INT NOT NULL,
  `project` VARCHAR(45) NOT NULL,
  `deadline` DATE NOT NULL,
  `yslovie` VARCHAR(45) NOT NULL,
  `zayavka` VARCHAR(45) NOT NULL,
  `in_additional` VARCHAR(45) NULL,
  PRIMARY KEY (`zayavka_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Profile` (
  `Profile_id` INT NOT NULL,
  `profile_fio` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `kategory_kategory` INT NOT NULL,
  `zayavka_zayavka_id` INT NULL,
  PRIMARY KEY (`Profile_id`),
  INDEX `fk_Profile_kategory_idx` (`kategory_kategory` ASC) VISIBLE,
  INDEX `fk_Profile_zayavka1_idx` (`zayavka_zayavka_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_kategory`
    FOREIGN KEY (`kategory_kategory`)
    REFERENCES `mydb`.`kategory` (`kategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_zayavka1`
    FOREIGN KEY (`zayavka_zayavka_id`)
    REFERENCES `mydb`.`zayavka` (`zayavka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
